# -*- coding: utf-8 -*-
"""Untitled15.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jcVlHI16B33zsu50rjGBWnfu9s6sMMz9
"""

# Full accuracy-focused fMRI GNN pipeline setup
# Run this cell first in Colab.
import os
import sys
import subprocess

PROJECT_DIR = "/content/fmri_IGA_accuracy_project1" if os.path.exists("/content") else "fmri_gnn_accuracy_project1"
os.makedirs(PROJECT_DIR, exist_ok=True)
os.chdir(PROJECT_DIR)
print(f"Working directory: {os.getcwd()}")

packages = [
    "torch",
    "torchvision",
    "torchaudio",
    "torch-geometric",
    "numpy",
    "pandas",
    "scipy",
    "scikit-learn",
    "nibabel",
    "nilearn",
    "matplotlib",
    "seaborn",
    "awscli",
    "tqdm",
]
subprocess.check_call([sys.executable, "-m", "pip", "install", "-q", *packages])
print("Packages installed.")

"""### Mount Google Drive and copy data"""

from google.colab import drive
drive.mount('/content/drive')

# =============================================================================
# NEW: Load REST-meta-MDD data from Google Drive
# =============================================================================

import os
import numpy as np
import pandas as pd
import scipy.io as sio
from tqdm import tqdm
from google.colab import drive

# 1. Mount Google Drive
drive.mount('/content/drive')

# 2. Path to your dataset (change if needed)
DATA_ROOT = '/content/drive/MyDrive/MDD_Dataset'

# --- BEGIN FIX ---
# Let's inspect the contents of DATA_ROOT/REST-meta-MDD-Phase1-Sharing/Results to find the correct ROI folder path.
# print(f"Contents of {DATA_ROOT}/REST-meta-MDD-Phase1-Sharing/Results:")
# !ls -F "{DATA_ROOT}/REST-meta-MDD-Phase1-Sharing/Results"
# print("--------------------------------------------------")
# print("Please check the output above and update the 'roi_folder' variable if necessary.")
# 3. Locate the ROI signals folder (adjust if your structure differs)
# Based on the previous 'ls' output, 'ROISignals_FunImgARCWF' is directly under 'Results'.
roi_folder = os.path.join(DATA_ROOT, 'REST-meta-MDD-Phase1-Sharing', 'Results', 'ROISignals_FunImgARCWF')

if not os.path.exists(roi_folder):
    print(f"ERROR: ROI folder not found at {roi_folder}.")
    print("Please update the 'roi_folder' variable in this cell with the correct path based on the 'ls' output above.")
    raise FileNotFoundError(f"ROI folder not found at {roi_folder}. Please check your dataset structure and modify 'roi_folder'.")
# --- END FIX ---

# 4. Locate the phenotypic file (look for .csv or .xlsx in DATA_ROOT)
pheno_files = [f for f in os.listdir(DATA_ROOT) if f.endswith(('.csv', '.xlsx'))]
if not pheno_files:
    raise FileNotFoundError(f"No phenotype file (.csv/.xlsx) found in {DATA_ROOT}")
pheno_path = os.path.join(DATA_ROOT, pheno_files[0])
print(f"Using phenotype file: {pheno_path}")

# 5. Load phenotypic data
if pheno_path.endswith('.csv'):
    pheno_df = pd.read_csv(pheno_path)
else:
    pheno_df = pd.read_excel(pheno_path)

# Print all columns for debugging
print("Columns in phenotypic data:", pheno_df.columns.tolist())

# 6. Identify the subject ID column (try common names)
id_candidates = ['SubjectID', 'participant_id', 'subid', 'ID', 'subject']
id_col = None
for col in id_candidates:
    if col in pheno_df.columns:
        id_col = col
        break
if id_col is None:
    # fallback: use first column
    id_col = pheno_df.columns[0]
print(f"Using '{id_col}' as subject identifier")

# 7. Identify diagnosis column (use 'HAMD' to derive labels)
diagnosis_col = 'HAMD'
if diagnosis_col not in pheno_df.columns:
    raise ValueError(f"Diagnosis column '{diagnosis_col}' not found in phenotype file.")
print(f"Using '{diagnosis_col}' as diagnosis column (labels will be derived from score)")

# 8. Identify age and sex columns (optional but recommended)
age_col = None
sex_col = None
for col in pheno_df.columns:
    if 'age' in col.lower():
        age_col = col
    if 'sex' in col.lower() or 'gender' in col.lower():
        sex_col = col

# 9. Build a mapping from subject ID to phenotype info
pheno_dict = {}
for _, row in pheno_df.iterrows():
    sub_id = str(row[id_col]).strip()
    # Normalize subject ID: remove 'sub-' if present, but keep the number
    if sub_id.startswith('sub-'):
        sub_id = sub_id[4:]
    pheno_dict[sub_id] = row.to_dict()

# 10. List all .mat files in roi_folder
mat_files = [f for f in os.listdir(roi_folder) if f.endswith('.mat')]
print(f"Found {len(mat_files)} .mat files")

# 11. Load each .mat, extract timeseries, and match with phenotype
X_list = []
Y_list = []
demo_list = []
subject_ids = []
skipped = []

for mat_file in tqdm(mat_files, desc="Loading ROI signals"):
    # Extract subject ID from filename (assuming pattern: ROISignals_sub-XXX.mat)
    sub_id = mat_file.replace('ROISignals_', '').replace('.mat', '')
    if sub_id.startswith('sub-'):
        sub_id = sub_id[4:]

    # Check if subject exists in phenotype
    if sub_id not in pheno_dict:
        skipped.append((sub_id, 'not in phenotype'))
        continue

    # Load .mat file
    mat_path = os.path.join(roi_folder, mat_file)
    try:
        mat_data = sio.loadmat(mat_path)
    except Exception as e:
        skipped.append((sub_id, f'load error: {e}'))
        continue

    # Extract the signal matrix - common key is 'ROISignals'
    # Shape: (n_timepoints, n_rois) or (n_rois, n_timepoints)
    if 'ROISignals' in mat_data:
        signal = mat_data['ROISignals']
    else:
        # fallback: take the first variable that is a 2D array
        for key in mat_data:
            if isinstance(mat_data[key], np.ndarray) and mat_data[key].ndim == 2:
                signal = mat_data[key]
                break
        else:
            skipped.append((sub_id, 'no 2D array found'))
            continue

    # Ensure shape is (n_rois, n_timepoints) -> we want ROIs first
    if signal.shape[0] < signal.shape[1]:
        # likely (time, roi) -> transpose
        signal = signal.T

    n_rois = signal.shape[0]
    # --- MODIFIED FIX: Changed expected ROI count from 116 to 1833 based on observed data ---
    if n_rois != 1833:
        skipped.append((sub_id, f'{n_rois} ROIs instead of 1833'))
        continue

    # --- MODIFIED FIX: Derive label from HAMD score and handle '[]' string ---
    hamd_score_raw = pheno_dict[sub_id][diagnosis_col]

    # Convert '[]' string to NaN
    if isinstance(hamd_score_raw, str) and hamd_score_raw == '[]':
        hamd_score = np.nan
    else:
        hamd_score = hamd_score_raw

    # A common threshold: HAMD score >= 7 for depression, < 7 for control/remission
    # Adjust this threshold if your specific study defines MDD differently
    if pd.isna(hamd_score): # Handle missing HAMD scores
        skipped.append((sub_id, 'missing HAMD score'))
        continue
    elif float(hamd_score) >= 7:
        label = 1  # Likely MDD
    else:
        label = 0  # Likely Control/Remission

    # Collect demographics
    age = float(pheno_dict[sub_id].get(age_col, np.nan)) if age_col else np.nan
    sex = float(pheno_dict[sub_id].get(sex_col, np.nan)) if sex_col else np.nan
    # Convert sex to numeric: M/F or 1/0
    if isinstance(sex, str):
        sex = 1.0 if sex.lower() in ['m', 'male'] else 0.0 if sex.lower() in ['f', 'female'] else np.nan
    else:
        try:
            sex = float(sex)
        except:
            sex = np.nan
    # Education: if not available, set to NaN (will be imputed later)
    edu = np.nan  # REST-meta-MDD may not have education; you can add if present

    X_list.append(signal)
    Y_list.append(label)
    demo_list.append([age, edu, sex])
    subject_ids.append(sub_id)

print(f"Successfully loaded {len(X_list)} subjects")
print(f"Skipped: {len(skipped)}")
if skipped:
    print("First skipped:", skipped[:5])

# 12. Align to a common number of timepoints (use minimum across subjects)
min_timepoints = min([ts.shape[1] for ts in X_list])
print(f"Using minimum timepoints: {min_timepoints}")
X_trimmed = [ts[:, :min_timepoints] for ts in X_list]
X = np.stack(X_trimmed, axis=0)   # shape: (N, 1833, T) now, assuming 1833 ROIs
Y = np.array(Y_list, dtype=np.int64)
demo = np.array(demo_list, dtype=float)

# 13. Impute missing demographics (age, edu, sex)
for col_idx in range(demo.shape[1]):
    col = demo[:, col_idx]
    if np.isnan(col).all():
        fill = 0.0
    else:
        fill = np.nanmean(col)
    demo[:, col_idx] = np.nan_to_num(col, nan=fill)

# 14. Save the prepared data into the same location expected by the IGA pipeline
MODEL_DATA_DIR = './REST-meta-MDD-Phase1-Sharing/AAL' # NOTE: This path implies AAL 116 ROIs, but data is now 1833 ROIs
os.makedirs(MODEL_DATA_DIR, exist_ok=True)

np.save(os.path.join(MODEL_DATA_DIR, 'X.npy'), X)
np.save(os.path.join(MODEL_DATA_DIR, 'Y.npy'), Y)
np.save(os.path.join(MODEL_DATA_DIR, 'subject_ids.npy'), np.array(subject_ids))
# Save dataset names (all from REST-meta-MDD)
dataset_names = np.array(['REST-meta-MDD'] * len(X))
np.save(os.path.join(MODEL_DATA_DIR, 'dataset_names.npy'), dataset_names)

# Save demographics as CSV
demographics_df = pd.DataFrame(demo, columns=['age', 'Edu', 'Sex'])
demographics_df['subject_id'] = subject_ids
demographics_df['dataset'] = 'REST-meta-MDD'
demographics_df.to_csv(os.path.join(MODEL_DATA_DIR, 'demographics_data.csv'), index=False)

print("\n=== Data preparation complete ===")
print(f"X shape: {X.shape} (subjects, ROIs, timepoints)")
print(f"Class distribution: {np.bincount(Y)}")
print(f"Data saved to {MODEL_DATA_DIR}/")

# =============================================================================
# REST-meta-MDD diagnosis-based dataset builder
# Paper-faithful labeling:
#   - uses diagnosis/group field, NOT HAMD threshold, when available
#   - keeps demographics: age, sex, education
#   - can target:
#       * POST_QC_FULL  -> 848 MDD + 794 HC
#       * BINARY_16SITE -> 814 MDD + 756 HC
#       * ALL_DIAGNOSIS -> all matched diagnosis-based subjects
#
# IMPORTANT:
# - This code scans all sheets in the phenotype Excel file to find the best one.
# - If no diagnosis/group column exists anywhere, it stops instead of inventing labels.
# - If site column exists, it can filter to the 16-site binary cohort.
# =============================================================================

import os
import re
import glob
import warnings
from collections import Counter, defaultdict

import numpy as np
import pandas as pd
import scipy.io as sio
from tqdm import tqdm

warnings.filterwarnings("ignore")

# -----------------------------------------------------------------------------
# 1. Safe Drive mount (Colab only)
# -----------------------------------------------------------------------------
IN_COLAB = False
try:
    import google.colab
    IN_COLAB = True
except:
    IN_COLAB = False

if IN_COLAB:
    from google.colab import drive
    if not os.path.exists('/content/drive/MyDrive'):
        drive.mount('/content/drive')
    else:
        print("Google Drive already mounted.")

# -----------------------------------------------------------------------------
# 2. User settings
# -----------------------------------------------------------------------------
DATA_ROOT = '/content/drive/MyDrive/MDD_Dataset' if IN_COLAB else './MDD_Dataset'
ROI_ROOT = os.path.join(DATA_ROOT, 'REST-meta-MDD-Phase1-Sharing', 'Results', 'ROISignals_FunImgARCWF')
PHENO_PATH = os.path.join(DATA_ROOT, 'REST-meta-MDD-PhenotypicData_WithHAMDSubItem_V4.xlsx')
OUTPUT_DIR = './REST_meta_MDD_paper_style'
os.makedirs(OUTPUT_DIR, exist_ok=True)

# Choose one:
#   'ALL_DIAGNOSIS'  -> all matched diagnosis-based subjects
#   'POST_QC_FULL'   -> target paper full post-QC cohort (848 MDD + 794 HC)
#   'BINARY_16SITE'  -> target paper MDD-vs-HC experiment (814 MDD + 756 HC)
TARGET_MODE = 'ALL_DIAGNOSIS'

# If None, keep dominant ROI count in current folder
# Set to 116 / 160 / 200 only if you truly have atlas ROI files
TARGET_ROI_COUNT = None

# Optional manual sheet override; keep None for auto-detect
FORCE_SHEET_NAME = None

# Optional manual column overrides; keep None for auto-detect
FORCE_ID_COL = None
FORCE_GROUP_COL = None
FORCE_SITE_COL = None
FORCE_AGE_COL = None
FORCE_SEX_COL = None
FORCE_EDU_COL = None

# Paper's 16-site binary MDD-vs-HC subset
PAPER_BINARY_SITES = {'1','2','7','8','9','10','11','13','14','15','17','19','20','21','22','23'}

# -----------------------------------------------------------------------------
# 3. Helper functions
# -----------------------------------------------------------------------------
def clean_text(x):
    if pd.isna(x):
        return None
    s = str(x).strip()
    if s == '' or s.lower() in {'nan', 'none', 'null'}:
        return None
    s = re.sub(r'\.0$', '', s)
    return s

def normalize_text(x):
    s = clean_text(x)
    return s.lower() if s is not None else None

def to_float(x):
    s = clean_text(x)
    if s is None:
        return np.nan
    try:
        return float(s)
    except:
        return np.nan

def sex_to_num(x):
    s = normalize_text(x)
    if s is None:
        return np.nan
    if s in {'m', 'male', 'man', '1'}:
        return 1.0
    if s in {'f', 'female', 'woman', '0', '2'}:
        return 0.0
    return np.nan

def extract_subject_id(mat_path):
    name = os.path.basename(mat_path).replace('.mat', '')
    name = re.sub(r'^ROISignals[_-]?', '', name, flags=re.IGNORECASE)
    return name

def make_id_candidates(x):
    s = clean_text(x)
    if s is None:
        return []
    cands = {s, s.lower(), s.upper()}

    if s.startswith('sub-'):
        base = s[4:]
        cands.update([base, base.lower(), base.upper()])
    else:
        cands.update([f"sub-{s}", f"sub-{s.lower()}", f"sub-{s.upper()}"])

    digits = re.sub(r'[^0-9]', '', s)
    if digits:
        try:
            n = int(digits)
            cands.update({
                str(n), f"{n:02d}", f"{n:03d}", f"{n:04d}",
                f"sub-{n}", f"sub-{n:02d}", f"sub-{n:03d}", f"sub-{n:04d}"
            })
        except:
            pass

    cands.add(s.replace('-', ''))
    return list(cands)

def find_column(df, exact=None, keywords=None):
    exact = exact or []
    keywords = keywords or []

    for c in exact:
        if c in df.columns:
            return c

    lowered = {str(c).lower(): c for c in df.columns}
    for c in exact:
        if c.lower() in lowered:
            return lowered[c.lower()]

    for col in df.columns:
        low = str(col).lower()
        for kw in keywords:
            if kw in low:
                return col
    return None

def get_signal_from_mat(mat_dict):
    if 'ROISignals' in mat_dict and isinstance(mat_dict['ROISignals'], np.ndarray) and mat_dict['ROISignals'].ndim == 2:
        return mat_dict['ROISignals']
    for k, v in mat_dict.items():
        if k.startswith('__'):
            continue
        if isinstance(v, np.ndarray) and v.ndim == 2:
            return v
    return None

def orient_signal(signal):
    signal = np.asarray(signal, dtype=np.float32)
    if signal.ndim != 2:
        return None
    if signal.shape[0] < signal.shape[1]:
        signal = signal.T
    return signal

def normalize_group_value(x):
    s = normalize_text(x)
    if s is None:
        return None

    if s in {'mdd', 'depression', 'major depressive disorder', 'patient', 'case', 'depressed'}:
        return 'MDD'
    if s in {'hc', 'healthy control', 'healthy controls', 'control', 'controls', 'healthy'}:
        return 'HC'
    if s in {'fedn', 'first episode drug naive', 'first-episode drug-naive', 'first episode drug-naive'}:
        return 'FEDN'
    if s in {'rmdd', 'recurrent mdd', 'recurrent depression'}:
        return 'rMDD'

    # soft matching
    if 'healthy' in s or s == 'hc':
        return 'HC'
    if 'recurrent' in s:
        return 'rMDD'
    if 'first' in s and 'episode' in s:
        return 'FEDN'
    if 'mdd' in s or 'depress' in s:
        return 'MDD'

    return None

def infer_group_from_episode_medication(row):
    first_ep = normalize_text(row.get('If first episode?', None))
    on_med = normalize_text(row.get('On medication?', None))

    yes_vals = {'yes', 'y', '1', 'true'}
    no_vals = {'no', 'n', '0', 'false'}

    if first_ep in yes_vals and on_med in no_vals:
        return 'FEDN'
    return None

def normalize_site_value(x):
    s = clean_text(x)
    if s is None:
        return None
    digits = re.findall(r'\d+', s)
    if digits:
        return str(int(digits[0]))
    return s

def sample_to_target(df, target_mdd, target_hc, random_state=42):
    mdd_df = df[df['group_final'] == 'MDD'].copy()
    hc_df = df[df['group_final'] == 'HC'].copy()

    if len(mdd_df) < target_mdd or len(hc_df) < target_hc:
        raise ValueError(
            f"Not enough subjects to match target counts. "
            f"Found MDD={len(mdd_df)}, HC={len(hc_df)}, need MDD={target_mdd}, HC={target_hc}"
        )

    mdd_keep = mdd_df.sample(n=target_mdd, random_state=random_state)
    hc_keep = hc_df.sample(n=target_hc, random_state=random_state)
    out = pd.concat([mdd_keep, hc_keep], axis=0).sort_values('subject_id').reset_index(drop=True)
    return out

# -----------------------------------------------------------------------------
# 4. Read all phenotype sheets (MODIFIED: Explicitly load MDD and Controls sheets)
# -----------------------------------------------------------------------------
if not os.path.exists(PHENO_PATH):
    raise FileNotFoundError(f"Phenotype file not found: {PHENO_PATH}")

xls = pd.ExcelFile(PHENO_PATH)
sheet_names = xls.sheet_names

print(f"Using phenotype file: {PHENO_PATH}")
print("Available sheets:", sheet_names)

sheet_dfs = {}
pheno_dfs_to_concat = []
chosen_sheet = "MDD and Controls sheets combined"

# Load MDD sheet
if 'MDD' in sheet_names:
    mdd_df = pd.read_excel(PHENO_PATH, sheet_name='MDD', dtype=str)
    mdd_df['group_norm'] = 'MDD'
    pheno_dfs_to_concat.append(mdd_df)
    print(f"\nSheet: MDD (rows: {len(mdd_df)}, columns: {mdd_df.columns.tolist()})")
else:
    print("WARNING: 'MDD' sheet not found.")

# Load Controls sheet
if 'Controls' in sheet_names:
    hc_df = pd.read_excel(PHENO_PATH, sheet_name='Controls', dtype=str)
    hc_df['group_norm'] = 'HC'
    pheno_dfs_to_concat.append(hc_df)
    print(f"\nSheet: Controls (rows: {len(hc_df)}, columns: {hc_df.columns.tolist()})")
else:
    print("WARNING: 'Controls' sheet not found.")

if not pheno_dfs_to_concat:
    raise ValueError("Neither 'MDD' nor 'Controls' sheet found in the phenotype file.")

pheno_df = pd.concat(pheno_dfs_to_concat, ignore_index=True, sort=False)

print(f"\nCombined phenotype dataframe (chosen sheet: {chosen_sheet})")
print("Columns:", pheno_df.columns.tolist())
print("Rows:", len(pheno_df))

# -----------------------------------------------------------------------------
# 5. Column detection (MODIFIED: Simplified group_col as it's now explicit)
# -----------------------------------------------------------------------------
id_col = FORCE_ID_COL or find_column(pheno_df, exact=['ID', 'SubjectID', 'participant_id'], keywords=['subject', 'participant', 'id'])
# group_col is now explicitly 'group_norm' which we created
group_col = 'group_norm'

site_col = FORCE_SITE_COL or find_column(pheno_df, exact=['Site', 'site', 'Center', 'Centre', 'Hospital'], keywords=['site', 'center', 'centre', 'hospital'])
age_col = FORCE_AGE_COL or find_column(pheno_df, exact=['Age'], keywords=['age'])
sex_col = FORCE_SEX_COL or find_column(pheno_df, exact=['Sex', 'Gender'], keywords=['sex', 'gender'])
edu_col = FORCE_EDU_COL or find_column(pheno_df, exact=['Education (years)', 'Education', 'Edu'], keywords=['education', 'edu'])

print("\nDetected columns")
print("ID column:", id_col)
print("Group/Diagnosis column:", group_col) # Should now always be 'group_norm'
print("Site column:", site_col)
print("Age column:", age_col)
print("Sex column:", sex_col)
print("Education column:", edu_col)

if id_col is None:
    raise ValueError("No subject ID column found in chosen phenotype sheet.")

# No need to raise ValueError for group_col being None, as it's now explicitly set.
if group_col not in pheno_df.columns:
    raise ValueError(f"Internal Error: '{group_col}' column not found after manual creation.")

# -----------------------------------------------------------------------------
# 6. Build phenotype lookup (MODIFIED: Removed redundant sheet selection logic)
# -----------------------------------------------------------------------------
records = []
for _, row in pheno_df.iterrows():
    rowd = row.to_dict()

    # raw_group now comes directly from the 'group_norm' column created earlier
    raw_group = rowd.get(group_col, None)
    group_norm = normalize_group_value(raw_group) # Re-normalize to ensure consistency

    if group_norm is None:
        # Attempt to infer if initial normalization failed, though it shouldn't for 'MDD'/'HC'
        inferred = infer_group_from_episode_medication(rowd)
        if inferred is not None:
            group_norm = inferred

    # collapse FEDN and rMDD into MDD for binary use when needed
    if group_norm in {'FEDN', 'rMDD'}:
        group_binary = 'MDD'
    elif group_norm == 'MDD':
        group_binary = 'MDD'
    elif group_norm == 'HC':
        group_binary = 'HC'
    else:
        group_binary = None

    rec = {
        'raw_row': rowd,
        'raw_id': rowd.get(id_col, None),
        'group_raw': raw_group,
        'group_norm': group_norm,
        'group_binary': group_binary,
        'site_norm': normalize_site_value(rowd.get(site_col, None)) if site_col else None,
        'age': to_float(rowd.get(age_col, np.nan)) if age_col else np.nan,
        'sex': sex_to_num(rowd.get(sex_col, np.nan)) if sex_col else np.nan,
        'edu': to_float(rowd.get(edu_col, np.nan)) if edu_col else np.nan
    }
    records.append(rec)

pheno_lookup = {}
for rec in records:
    for cand in make_id_candidates(rec['raw_id']):
        pheno_lookup[cand] = rec

print("\nPhenotype summary")
group_counts = Counter([r['group_norm'] for r in records if r['group_norm'] is not None])
binary_counts = Counter([r['group_binary'] for r in records if r['group_binary'] is not None])
site_counts = Counter([r['site_norm'] for r in records if r['site_norm'] is not None])
print("Detailed groups:", group_counts)
print("Binary groups:", binary_counts)
print("Sites found:", len(site_counts))

# -----------------------------------------------------------------------------
# 7. Load ROI files (Previous Section 8)
# -----------------------------------------------------------------------------
mat_files = sorted(glob.glob(os.path.join(ROI_ROOT, '**', '*.mat'), recursive=True))
print(f"\nFound {len(mat_files)} .mat files under ROI root")

loaded = []
skipped = []

for mat_path in tqdm(mat_files, desc="Loading ROI signals"):
    sub_id = extract_subject_id(mat_path)

    rec = None
    for cand in make_id_candidates(sub_id):
        if cand in pheno_lookup:
            rec = pheno_lookup[cand]
            break

    if rec is None:
        skipped.append((sub_id, 'not in phenotype'))
        continue

    try:
        mat_data = sio.loadmat(mat_path)
    except Exception as e:
        skipped.append((sub_id, f'load error: {e}'))
        continue

    signal = get_signal_from_mat(mat_data)
    if signal is None:
        skipped.append((sub_id, 'no 2D ROI signal found'))
        continue

    signal = orient_signal(signal)
    if signal is None:
        skipped.append((sub_id, 'invalid signal shape'))
        continue

    n_rois, n_timepoints = signal.shape

    loaded.append({
        'subject_id': sub_id,
        'signal': signal,
        'n_rois': n_rois,
        'n_timepoints': n_timepoints,
        'group_norm': rec['group_norm'],
        'group_binary': rec['group_binary'],
        'site_norm': rec['site_norm'],
        'age': rec['age'],
        'sex': rec['sex'],
        'edu': rec['edu']
    })

print(f"\nLoaded subjects before ROI filtering: {len(loaded)}")
print(f"Skipped before ROI filtering: {len(skipped)}")

roi_counter = Counter(x['n_rois'] for x in loaded)
print("ROI count distribution:", roi_counter)

if len(roi_counter) == 0:
    raise ValueError("No valid ROI signals loaded.")

if TARGET_ROI_COUNT is None:
    TARGET_ROI_COUNT = roi_counter.most_common(1)[0][0]

print(f"Using TARGET_ROI_COUNT = {TARGET_ROI_COUNT}")

filtered = []
for item in loaded:
    if item['n_rois'] != TARGET_ROI_COUNT:
        skipped.append((item['subject_id'], f"{item['n_rois']} ROIs instead of {TARGET_ROI_COUNT}"))
        continue
    filtered.append(item)

print(f"Subjects after ROI filtering: {len(filtered)}")

if TARGET_ROI_COUNT not in {116, 160, 200}:
    print(
        f"WARNING: Current ROI count is {TARGET_ROI_COUNT}, not one of the paper's atlas counts "
        f"(116, 160, 200). This means the data representation does not exactly match the paper's "
        f"atlas-preprocessing description."
    )

# -----------------------------------------------------------------------------
# 8. Keep only diagnosis-based MDD/HC rows (Previous Section 9)
# -----------------------------------------------------------------------------
dataset_rows = []
for item in filtered:
    if item['group_binary'] not in {'MDD', 'HC'}:
        skipped.append((item['subject_id'], f"unsupported group {item['group_norm']}"))
        continue

    dataset_rows.append({
        'subject_id': item['subject_id'],
        'signal': item['signal'],
        'n_timepoints': item['n_timepoints'],
        'group_detail': item['group_norm'],
        'group_final': item['group_binary'],
        'label': 1 if item['group_binary'] == 'MDD' else 0,
        'site': item['site_norm'],
        'age': item['age'],
        'sex': item['sex'],
        'edu': item['edu']
    })

df = pd.DataFrame(dataset_rows)
print(f"\nSubjects after diagnosis-based selection: {len(df)}")
if len(df) == 0:
    raise ValueError("No diagnosis-based MDD/HC subjects found after filtering.")

print("Diagnosis distribution:", df['group_final'].value_counts(dropna=False).to_dict())
print("Detailed group distribution:", df['group_detail'].value_counts(dropna=False).to_dict())

# -----------------------------------------------------------------------------
# 9. Apply target cohort mode (Previous Section 10)
# -----------------------------------------------------------------------------
if TARGET_MODE == 'ALL_DIAGNOSIS':
    final_df = df.copy()

elif TARGET_MODE == 'POST_QC_FULL':
    # paper target: 848 MDD + 794 HC
    final_df = sample_to_target(df, target_mdd=848, target_hc=794, random_state=42)

elif TARGET_MODE == 'BINARY_16SITE':
    if 'site' not in df.columns or df['site'].isnull().all():
        raise ValueError(
            "Cannot build BINARY_16SITE subset because no site column was found/matched."
        )

    df16 = df[df['site'].astype(str).isin(PAPER_BINARY_SITES)].copy()
    print("After 16-site filter:", len(df16))
    print("16-site distribution:", df16['group_final'].value_counts(dropna=False).to_dict())

    final_df = sample_to_target(df16, target_mdd=814, target_hc=756, random_state=42)

else:
    raise ValueError(f"Unknown TARGET_MODE: {TARGET_MODE}")

print(f"\nFinal dataset size: {len(final_df)}")
print("Final class distribution:", final_df['group_final'].value_counts().to_dict())

# -----------------------------------------------------------------------------
# 10. Build arrays (Previous Section 11)
# -----------------------------------------------------------------------------
min_timepoints = int(final_df['n_timepoints'].min())
print("Using minimum timepoints:", min_timepoints)

X = np.stack([sig[:, :min_timepoints] for sig in final_df['signal'].tolist()], axis=0).astype(np.float32)
Y = final_df['label'].to_numpy(dtype=np.int64)
subject_ids = final_df['subject_id'].astype(str).to_numpy(dtype=object)
demo = final_df[['age', 'edu', 'sex']].to_numpy(dtype=np.float32).copy() # Added .copy() here to ensure writability

for j in range(demo.shape[1]):
    col = demo[:, j]
    fill = 0.0 if np.isnan(col).all() else np.nanmean(col)
    demo[:, j] = np.nan_to_num(col, nan=fill)

summary_df = final_df[['subject_id', 'group_detail', 'group_final', 'label', 'site', 'age', 'edu', 'sex']].copy()
summary_df.rename(columns={'edu': 'Education', 'sex': 'Sex', 'age': 'Age'}, inplace=True)

# -----------------------------------------------------------------------------
# 11. Save outputs (Previous Section 12)
# -----------------------------------------------------------------------------
np.save(os.path.join(OUTPUT_DIR, 'X.npy'), X)
np.save(os.path.join(OUTPUT_DIR, 'Y.npy'), Y)
np.save(os.path.join(OUTPUT_DIR, 'demo.npy'), demo)
np.save(os.path.join(OUTPUT_DIR, 'subject_ids.npy'), subject_ids)

summary_df.to_csv(os.path.join(OUTPUT_DIR, 'demographics_data.csv'), index=False)
pd.DataFrame(skipped, columns=['subject_id', 'reason']).to_csv(
    os.path.join(OUTPUT_DIR, 'skipped_subjects.csv'), index=False
)

with open(os.path.join(OUTPUT_DIR, 'info.txt'), 'w') as f:
    f.write(f"TARGET_MODE={TARGET_MODE}\n")
    f.write(f"CHOSEN_SHEET={chosen_sheet}\n")
    f.write(f"ID_COL={id_col}\n")
    f.write(f"GROUP_COL={group_col}\n")
    f.write(f"SITE_COL={site_col}\n")
    f.write(f"AGE_COL={age_col}\n")
    f.write(f"SEX_COL={sex_col}\n")
    f.write(f"EDU_COL={edu_col}\n")
    f.write(f"TARGET_ROI_COUNT={TARGET_ROI_COUNT}\n")
    f.write(f"NUM_SUBJECTS={len(subject_ids)}\n")
    f.write(f"TIMEPOINTS={min_timepoints}\n")
    f.write(f"X_SHAPE={X.shape}\n")
    f.write(f"CLASS_DISTRIBUTION={Counter(final_df['group_final'])}\n")

# -----------------------------------------------------------------------------
# 12. Final report (Previous Section 13)
# -----------------------------------------------------------------------------
print("\n=== Dataset preparation complete ===")
print("Chosen phenotype sheet:", chosen_sheet)
print("ROI count used:", TARGET_ROI_COUNT)
print("X shape:", X.shape)
print("Y shape:", Y.shape)
print("Demo shape:", demo.shape)
print("Class distribution:", np.bincount(Y))
print("Saved to:", OUTPUT_DIR)
print("\nFirst rows:")
print(summary_df.head())

# ============================================================
# IGA: Independent Graph Analysis (FIXED VERSION)
# Fixes: PCA unused bug, severe overfitting, no augmentation,
#        over-regularization, LR schedule, small batch size
# Adds: PCA injection, Mixup, SWA, Cosine Annealing, Residual,
#        Temporal augmentation (train only), Reduced capacity
# ============================================================

import os, random, time, copy
import numpy as np
import pandas as pd
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from torch_geometric.data import Data, DataLoader
from torch_geometric.nn import ChebConv, global_mean_pool
from torch_geometric.utils import dense_to_sparse
from sklearn.preprocessing import StandardScaler
from sklearn.covariance import LedoitWolf
from sklearn.neighbors import kneighbors_graph
from sklearn.metrics import accuracy_score, f1_score, roc_auc_score
from sklearn.model_selection import StratifiedKFold, train_test_split
from sklearn.decomposition import FastICA
from scipy.stats import kurtosis
import warnings
warnings.filterwarnings("ignore")

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

SEED = 89
ATLAS = "Custom_1833ROIs" # Updated ATLAS name to reflect actual ROI count
DATASET_DIR = "./REST_meta_MDD_paper_style" # Corrected path to processed data

random.seed(SEED); np.random.seed(SEED); torch.manual_seed(SEED)

# Dynamically set N_ROIS to match the prepared data (1833 from previous step)
N_ROIS = 1833 # Corrected N_ROIS to match the prepared data
# Removed the 'if ATLAS == "AAL"' check as we are using a custom ROI count

# ============================================================
# FIXED HYPERPARAMETERS
# ============================================================
WINDOW_SIZE = 60            # Keep
STRIDE = 15                 # FIX: 30 -> 15 (more augmentation windows)
K_NEIGHBORS = 10            # Keep
HIDDEN_DIM = 32             # FIX: 64 -> 32 (halve capacity, ~78K -> ~30K params)
CHEBY_K = 2                 # Keep
DROPOUT = 0.5               # FIX: 0.4 -> 0.5 (stronger regularization)
LEARNING_RATE = 0.0005     # FIX: 0.001 -> 0.0005 (slower, more stable)
WEIGHT_DECAY = 1e-3         # FIX: 5e-3 -> 1e-3 (reduce over-regularization)
NUM_EPOCHS = 300
PATIENCE = 40               # FIX: 60 -> 40 (stop earlier, model overfits fast)
BATCH_SIZE = 16             # FIX: 8 -> 16 (more stable gradients)
N_SPLITS = 5
NUM_CLASSES = 2
LAMBDA_MAX = 0.002
ICA_COMPONENTS = 20
LABEL_SMOOTHING = 0.05      # FIX: 0.1 -> 0.05 (less smoothing)
MIXUP_ALPHA = 0.4           # NEW: Mixup augmentation strength
SWA_START = 30              # NEW: Start SWA after epoch 30
DECorR_WEIGHT = 0.01        # FIX: 0.001 -> 0.01 (stronger decorrelation)
USE_AUGMENTATION_TRAIN = True  # FIX: enable augmentation for training only


# ============================================================
# ICA functions (UNCHANGED)
# ============================================================
def fit_subject_ica(sub_data, n_components=20, random_state=89):
    X = sub_data.T
    scaler = StandardScaler()
    X_scaled = scaler.fit_transform(X)
    ica = FastICA(n_components=n_components, whiten="unit-variance",
                  random_state=random_state, max_iter=3000, tol=1e-7)
    S = ica.fit_transform(X_scaled)
    A = ica.mixing_
    return ica, scaler, X_scaled, S, A


def automatic_bad_ica_components(X_scaled, S, A,
                                  high_freq_threshold=0.35,
                                  global_corr_threshold=0.40,
                                  kurtosis_threshold=12.0,
                                  spatial_concentration_threshold=0.35):
    global_signal = X_scaled.mean(axis=1)
    bad_components = []
    rows = []
    for c in range(S.shape[1]):
        comp = S[:, c]
        if np.std(comp) == 0 or np.std(global_signal) == 0:
            abs_corr_global = 0.0
        else:
            abs_corr_global = abs(np.corrcoef(comp, global_signal)[0, 1])
        power = np.abs(np.fft.rfft(comp)) ** 2
        if power.sum() == 0:
            high_freq_ratio = 0.0
        else:
            cutoff = int(len(power) * 0.60)
            high_freq_ratio = power[cutoff:].sum() / power.sum()
        kurt_excess = float(kurtosis(comp, fisher=True, bias=False))
        abs_loading = np.abs(A[:, c])
        if abs_loading.sum() == 0:
            spatial_concentration = 0.0
        else:
            spatial_concentration = abs_loading.max() / abs_loading.sum()
        is_bad = (high_freq_ratio >= high_freq_threshold or
                  abs_corr_global >= global_corr_threshold or
                  kurt_excess >= kurtosis_threshold or
                  spatial_concentration >= spatial_concentration_threshold)
        if is_bad:
            bad_components.append(c)
        rows.append({
            "component_1based": c + 1,
            "abs_corr_with_global_signal": abs_corr_global,
            "high_frequency_power_ratio": high_freq_ratio,
            "kurtosis_excess": kurt_excess,
            "spatial_concentration": spatial_concentration,
            "auto_removed": is_bad
        })
    return bad_components, pd.DataFrame(rows)


def reconstruct_without_bad_components(ica, scaler, S, bad_components):
    S_clean = S.copy()
    for comp in bad_components:
        S_clean[:, comp] = 0.0
    X_clean_scaled = ica.inverse_transform(S_clean)
    X_clean = scaler.inverse_transform(X_clean_scaled)
    return X_clean.T, S_clean


def apply_auto_ica_denoising(X, n_components=20, random_state=89,
                             save_report_path="auto_ica_removed_components.csv"):
    X_clean_all = []
    report_tables = []
    for i, sub_data in enumerate(X):
        subject_id = f"subject_{i}"
        print(f"Automatic ICA cleaning: {subject_id}")
        ica, scaler, X_scaled, S, A = fit_subject_ica(sub_data, n_components, random_state)
        bad_components, report = automatic_bad_ica_components(X_scaled, S, A)
        X_clean, S_clean = reconstruct_without_bad_components(ica, scaler, S, bad_components)
        kept = [c for c in range(n_components) if c not in bad_components]
        report["subject_id"] = subject_id
        report["removed_components_1based"] = ",".join(str(c+1) for c in bad_components)
        report_tables.append(report)
        X_clean_all.append(X_clean)
        print(f"{subject_id}: auto removed ICs {[c+1 for c in bad_components]} | "
              f"dimension {N_ROIS} -> {n_components} -> {len(kept)} clean components") # N_ROIS is now correct here
    full_report = pd.concat(report_tables, ignore_index=True)
    full_report.to_csv(save_report_path, index=False)
    print(f"Automatic ICA report saved to: {save_report_path}")
    return np.array(X_clean_all)


def load_data(use_ica=True):
    # Corrected DATASET_DIR is used here
    X = np.load(f"{DATASET_DIR}/X.npy")
    Y = np.load(f"{DATASET_DIR}/Y.npy")
    if use_ica:
        n_comp = ICA_COMPONENTS
        clean_path = f"{DATASET_DIR}/X_auto_ica_clean.npy"
        if os.path.exists(clean_path):
            print("Loading cached automatic ICA cleaned data")
            X = np.load(clean_path)
        else:
            print("Running automatic ICA artifact removal + dimensionality reduction")
            X = apply_auto_ica_denoising(
                X, n_components=n_comp, random_state=SEED,
                save_report_path=f"{DATASET_DIR}/auto_ica_removed_components.csv"
            )
            np.save(clean_path, X)
            print(f"Saved automatic ICA cleaned data to: {clean_path}")
    else:
        print("Running WITHOUT ICA")
    demo_df = pd.read_csv(f"{DATASET_DIR}/demographics_data.csv")
    demo = np.zeros((len(X), 3))
    demo[:, 0] = StandardScaler().fit_transform(demo_df["Age"].values.reshape(-1, 1)).ravel()
    demo[:, 1] = StandardScaler().fit_transform(demo_df["Education"].values.reshape(-1, 1)).ravel()
    demo[:, 2] = demo_df["Sex"].values
    print(f"Final X shape: {X.shape} | Class dist: {np.bincount(Y)}")
    return X, Y, demo


# ============================================================
# Online PCA (UNCHANGED)
# ============================================================
class OnlineGraphPCA:
    """CCIPCA for streaming graph adjacency matrices."""
    def __init__(self, n_features, n_components=20, amnesic_factor=0):
        self.n_features = n_features
        self.n_components = n_components
        self.amnesic_factor = amnesic_factor
        self.n = 0
        self.mean = np.zeros(n_features)
        self.V = np.zeros((n_features, n_components))
        self.U = np.zeros((n_features, n_components))
        self.D = np.zeros(n_components)

    def update(self, x):
        self.n += 1
        if self.n == 1:
            self.V[:, 0] = x
            self.U[:, 0] = x / (np.linalg.norm(x) + 1e-10)
            self.D[0] = np.linalg.norm(x)
            return
        old_mean = self.mean.copy()
        self.mean = (self.n - 1) / self.n * old_mean + 1/self.n * x
        x_centered = x - old_mean
        x_rem = x_centered.copy()
        for j in range(self.n_components):
            if self.n > 1:
                norm_v = np.linalg.norm(self.V[:, j]) + 1e-10
                if self.amnesic_factor > 0:
                    w = (self.n - self.amnesic_factor) / (self.n + 1)
                else:
                    w = self.n / (self.n + 1)
                proj = x_rem.T @ (self.V[:, j] / norm_v)
                self.V[:, j] = w * self.V[:, j] + (1 - w) * proj * x_rem
                norm_new = np.linalg.norm(self.V[:, j]) + 1e-10
                self.U[:, j] = self.V[:, j] / norm_new
                self.D[j] = norm_new
                x_rem = x_rem - (x_rem.T @ self.U[:, j]) * self.U[:, j]
            else:
                self.V[:, j] = x_rem
                norm_v = np.linalg.norm(x_rem) + 1e-10
                self.U[:, j] = x_rem / norm_v
                self.D[j] = norm_v
                x_rem = x_rem - (x_rem.T @ self.U[:, j]) * self.U[:, j]

    def get_components(self, n=None):
        if n is None:
            n = self.n_components
        return self.U[:, :n], self.D[:n]

    def get_reconstruction(self, n=None):
        if n is None:
            n = self.n_components
        return self.U[:, :n] @ (self.D[:n, None] * self.U[:, :n].T)


# ============================================================
# FIXED MODEL: PCA injection + reduced capacity + residual
# ============================================================
class IGA_Model(nn.Module):
    """IGA model with PCA feature injection and reduced capacity."""
    def __init__(self, in_channels, num_classes, n_rois, n_pca_components=20,
                 hidden=32, K=2, dropout=0.5, drop_edge_ratio=0.2):
        super().__init__()
        self.n_rois = n_rois
        self.n_pca = n_pca_components
        self.hidden = hidden
        self.dropout = dropout
        self.drop_edge_ratio = drop_edge_ratio

        # FIX: PCA feature projection layer (was missing entirely)
        self.pca_proj = nn.Linear(n_rois, hidden)

        # Hybrid component weighting (kept from original)
        self.mixing = nn.Parameter(torch.randn(in_channels, n_pca_components) * 0.01)
        self.selector = nn.Sequential(
            nn.Linear(n_pca_components, n_pca_components),
            nn.ReLU(),
            nn.Linear(n_pca_components, n_pca_components),
            nn.Sigmoid()
        )

        # 2 Cheb layers (removed comp_encoder to reduce params)
        self.conv1 = ChebConv(in_channels + hidden, hidden, K=K, normalization="sym")
        self.norm1 = nn.LayerNorm(hidden)

        # FIX: Residual connection for better gradient flow
        self.residual = nn.Linear(in_channels + hidden, hidden)

        self.conv2 = ChebConv(hidden, hidden, K=K, normalization="sym")
        self.norm2 = nn.LayerNorm(hidden)

        # Attention-based global pooling
        self.attn_pool = nn.Sequential(
            nn.Linear(hidden, hidden // 2),
            nn.Tanh(),
            nn.Linear(hidden // 2, 1)
        )

        self.classifier = nn.Sequential(
            nn.Linear(hidden, hidden // 2),
            nn.ReLU(),
            nn.Dropout(dropout),
            nn.Linear(hidden // 2, num_classes)
        )

    def drop_edge(self, edge_index, edge_attr, drop_ratio):
        if not self.training or drop_ratio == 0:
            return edge_index, edge_attr
        num_edges = edge_index.size(1)
        mask = torch.rand(num_edges, device=edge_index.device) > drop_ratio
        if edge_attr is not None:
            edge_attr = edge_attr[mask]
        return edge_index[:, mask], edge_attr

    def forward(self, data, pca_components):
        x = data.x
        edge_index = data.edge_index
        edge_attr = data.edge_attr if hasattr(data, "edge_attr") else None
        batch = data.batch

        # DropEdge regularization
        edge_index, edge_attr = self.drop_edge(edge_index, edge_attr, self.drop_edge_ratio)

        # ============================================================
        # FIX: Actually USE pca_components in forward (was passed but ignored)
        # ============================================================
        if pca_components is not None and len(pca_components) > 0:
            pca_stacked = torch.stack(pca_components, dim=0)  # (n_pca, N_ROIS, N_ROIS)
            pca_node_feat = pca_stacked.mean(dim=0)            # (N_ROIS, N_ROIS)
            pca_proj = self.pca_proj(pca_node_feat)            # (N_ROIS, hidden)
            pca_proj = F.dropout(pca_proj, p=self.dropout, training=self.training)
            # FIX: Repeat pca_proj for each graph in the batch
            batch_size = batch.max().item() + 1
            pca_proj = pca_proj.repeat(batch_size, 1)  # (batch * N_ROIS, hidden)
        else:
            pca_proj = torch.zeros(x.size(0), self.hidden, device=x.device)

        # Hybrid component weighting (kept from original)
        S = x @ self.mixing
        alpha = self.selector(S)
        weighted_x = x * alpha.mean(dim=1, keepdim=True)

        # Combine input with PCA projected features
        x_combined = torch.cat([x, pca_proj], dim=-1)

        # Cheb layer 1
        x1 = self.conv1(x_combined, edge_index, edge_attr)
        x1 = self.norm1(x1)
        x1 = F.relu(x1)
        x1 = F.dropout(x1, p=self.dropout, training=self.training)

        # FIX: Residual connection
        x1 = x1 + self.residual(x_combined)

        # Cheb layer 2
        x2 = self.conv2(x1, edge_index, edge_attr)
        x2 = self.norm2(x2)
        x2 = F.relu(x2)
        x2 = F.dropout(x2, p=self.dropout, training=self.training)

        # Attention-based global pooling
        attn_scores = self.attn_pool(x2).squeeze(-1)
        attn_weights = torch.sigmoid(attn_scores)
        graph_emb = global_mean_pool(x2 * attn_weights.unsqueeze(-1), batch)

        out = self.classifier(graph_emb)
        return out, graph_emb, x2, alpha


def decorrelation_loss(emb, eps=1e-5):
    if emb.size(0) < 2:
        return emb.sum() * 0.0
    emb_centered = emb - emb.mean(dim=0, keepdim=True)
    cov = torch.mm(emb_centered.T, emb_centered) / (emb.size(0) - 1 + eps)
    off_diag = cov - torch.diag(torch.diag(cov))
    loss = torch.norm(off_diag, p='fro') ** 2
    return loss


# ============================================================
# Graph construction (UNCHANGED)
# ============================================================
def compute_graph_adj(corr_mat, method='knn_shrinkage', k=10):
    if method == 'knn_shrinkage':
        abs_corr = np.abs(corr_mat)
        np.fill_diagonal(abs_corr, 0.0)
        k_eff = min(k, corr_mat.shape[0] - 1)
        knn = kneighbors_graph(abs_corr, n_neighbors=k_eff, mode='connectivity',
                               include_self=False)
        knn_arr = knn.toarray()
        adj_mask = np.maximum(knn_arr, knn_arr.T)
        weighted_adj = corr_mat * adj_mask
        np.fill_diagonal(weighted_adj, 0.0)
        weighted_adj = np.nan_to_num(weighted_adj, nan=0.0, posinf=0.0, neginf=0.0)
        return weighted_adj.astype(np.float32)
    else:
        raise ValueError(f"Unknown method: {method}")


def build_graphs_iga(subject_list, demo_list, label_list, window_size, stride,
                     use_augmentation=False, graph_method='knn_shrinkage', k=10):
    graphs = []
    for sub_idx, (sub, dem, lab) in enumerate(zip(subject_list, demo_list, label_list)):
        n_rois, n_time = sub.shape
        if use_augmentation and n_time >= window_size:
            for start in range(0, n_time - window_size + 1, stride):
                end = start + window_size
                window = sub[:, start:end]
                w = np.hamming(window.shape[1])
                window_tapered = window * w[np.newaxis, :]
                try:
                    lw = LedoitWolf(assume_centered=False)
                    lw.fit(window_tapered.T)
                    cov = lw.covariance_
                except:
                    cov = np.cov(window_tapered.T, rowvar=False, bias=False)
                cov = np.nan_to_num(cov, nan=0.0, posinf=0.0, neginf=0.0)
                diag = np.clip(np.diag(cov).copy(), 0.0, None)
                d = np.sqrt(diag + 1e-6)
                corr = cov / np.outer(d, d)
                corr = np.nan_to_num(corr, nan=0.0, posinf=0.0, neginf=0.0)
                corr = np.clip(corr, -0.999, 0.999)
                np.fill_diagonal(corr, 1.0)
                corr_clip = np.clip(corr, -1+1e-3, 1-1e-3)
                fisher = 0.5 * np.log((1 + corr_clip) / (1 - corr_clip))
                fisher = np.nan_to_num(fisher, nan=0.0, posinf=3.0, neginf=-3.0)
                fisher = np.clip(fisher, -3.0, 3.0)
                adj = compute_graph_adj(fisher, method=graph_method, k=k)
                demo_exp = np.tile(dem.reshape(1, -1), (n_rois, 1))
                node_feat = np.concatenate((fisher, demo_exp), axis=1)
                node_feat = np.nan_to_num(node_feat, nan=0.0, posinf=0.0, neginf=0.0)
                x = torch.from_numpy(node_feat).float()
                edge_index, edge_attr = dense_to_sparse(torch.from_numpy(adj).float())
                edge_attr = torch.abs(edge_attr)
                edge_attr = torch.nan_to_num(edge_attr, nan=0.0, posinf=0.0, neginf=0.0)
                g = Data(x=x, edge_index=edge_index, edge_attr=edge_attr.float(),
                         y=torch.tensor([lab], dtype=torch.long))
                g.demographics = torch.from_numpy(dem).float().unsqueeze(0)
                g.num_nodes = n_rois
                g.adj_matrix = torch.from_numpy(adj).float()
                graphs.append(g)
        else:
            window = sub
            w = np.hamming(window.shape[1])
            window_tapered = window * w[np.newaxis, :]
            try:
                lw = LedoitWolf(assume_centered=False)
                lw.fit(window_tapered.T)
                cov = lw.covariance_
            except:
                cov = np.cov(window_tapered.T, rowvar=False, bias=False)
            cov = np.nan_to_num(cov, nan=0.0, posinf=0.0, neginf=0.0)
            diag = np.clip(np.diag(cov).copy(), 0.0, None)
            d = np.sqrt(diag + 1e-6)
            corr = cov / np.outer(d, d)
            corr = np.nan_to_num(corr, nan=0.0, posinf=0.0, neginf=0.0)
            corr = np.clip(corr, -0.999, 0.999)
            np.fill_diagonal(corr, 1.0)
            corr_clip = np.clip(corr, -1+1e-3, 1-1e-3)
            fisher = 0.5 * np.log((1 + corr_clip) / (1 - corr_clip))
            fisher = np.nan_to_num(fisher, nan=0.0, posinf=3.0, neginf=-3.0)
            fisher = np.clip(fisher, -3.0, 3.0)
            adj = compute_graph_adj(fisher, method=graph_method, k=k)
            demo_exp = np.tile(dem.reshape(1, -1), (n_rois, 1))
            node_feat = np.concatenate((fisher, demo_exp), axis=1)
            node_feat = np.nan_to_num(node_feat, nan=0.0, posinf=0.0, neginf=0.0)
            x = torch.from_numpy(node_feat).float()
            edge_index, edge_attr = dense_to_sparse(torch.from_numpy(adj).float())
            edge_attr = torch.abs(edge_attr)
            edge_attr = torch.nan_to_num(edge_attr, nan=0.0, posinf=0.0, neginf=0.0)
            g = Data(x=x, edge_index=edge_index, edge_attr=edge_attr.float(),
                     y=torch.tensor([lab], dtype=torch.long))
            g.demographics = torch.from_numpy(dem).float().unsqueeze(0)
            g.num_nodes = n_rois
            g.adj_matrix = torch.from_numpy(adj).float()
            graphs.append(g)
    print(f"Created {len(graphs)} graphs")
    return graphs


# ============================================================
# NEW: Mixup helper for graph-level classification
# ============================================================
def mixup_data(labels, alpha=0.4):
    """Return lambda and permutation indices for Mixup."""
    if alpha > 0:
        lam = float(np.random.beta(alpha, alpha))
    else:
        lam = 1.0
    lam = max(lam, 1.0 - lam)
    batch_size = labels.size(0)
    perm = torch.randperm(batch_size, device=labels.device)
    return lam, perm


# ============================================================
# FIXED TRAINING: Mixup + Cosine Annealing + SWA
# ============================================================
def train_fold_iga(train_graphs, val_graphs, test_graphs, fold_id, online_pca):
    print(f"\n{'='*60}")
    print(f"Fold {fold_id}: Training IGA on {len(train_graphs)} graphs")
    print(f"{'='*60}")

    y_train = [g.y.item() for g in train_graphs]
    class_counts = np.bincount(y_train)
    total = len(y_train)
    weights_np = total / (NUM_CLASSES * np.maximum(class_counts, 1))
    class_weights = torch.tensor(weights_np ** 0.5, dtype=torch.float).to(device)
    print(f"Computed class weights: {class_weights.cpu().numpy()}")

    model = IGA_Model(
        in_channels=train_graphs[0].x.size(1),
        num_classes=NUM_CLASSES,
        n_rois=N_ROIS,
        n_pca_components=online_pca.n_components,
        hidden=HIDDEN_DIM,
        K=CHEBY_K,
        dropout=DROPOUT,
        drop_edge_ratio=0.2
    ).to(device)

    n_params = sum(p.numel() for p in model.parameters())
    print(f"Model parameters: {n_params:,}")

    optimizer = optim.AdamW(model.parameters(), lr=LEARNING_RATE,
                            weight_decay=WEIGHT_DECAY)

    # FIX: Cosine annealing with warm restarts (replaces ReduceLROnPlateau)
    scheduler = optim.lr_scheduler.CosineAnnealingWarmRestarts(
        optimizer, T_0=50, T_mult=2, eta_min=1e-6
    )

    train_loader = DataLoader(train_graphs, batch_size=BATCH_SIZE, shuffle=True)
    val_loader = DataLoader(val_graphs, batch_size=BATCH_SIZE, shuffle=False)
    test_loader = DataLoader(test_graphs, batch_size=BATCH_SIZE, shuffle=False)

    best_val_f1 = 0
    best_test_metrics = None
    patience_counter = 0

    # NEW: SWA setup
    swa_model = copy.deepcopy(model)
    swa_n = 0
    swa_active = False

    for epoch in range(1, NUM_EPOCHS + 1):
        model.train()
        total_loss = 0
        all_preds, all_labels = [], []

        for batch in train_loader:
            batch = batch.to(device)
            pca_U, pca_D = online_pca.get_components(n=online_pca.n_components)
            pca_comps = [
                torch.from_numpy(pca_U[:, i].reshape(N_ROIS, N_ROIS)).float().to(device)
                for i in range(pca_U.shape[1])
            ]

            # NEW: Mixup augmentation (output-level)
            if MIXUP_ALPHA > 0 and epoch > 5:
                lam, perm = mixup_data(batch.y, MIXUP_ALPHA)
                out, graph_emb, node_emb, alpha = model(batch, pca_comps)

                y_a, y_b = batch.y, batch.y[perm]
                loss = (lam * F.cross_entropy(out, y_a, weight=class_weights,
                        label_smoothing=LABEL_SMOOTHING)
                        + (1 - lam) * F.cross_entropy(out, y_b, weight=class_weights,
                        label_smoothing=LABEL_SMOOTHING))
            else:
                out, graph_emb, node_emb, alpha = model(batch, pca_comps)
                loss = F.cross_entropy(out, batch.y, weight=class_weights,
                                       label_smoothing=LABEL_SMOOTHING)

            # Decorrelation regularization
            loss_decorr = decorrelation_loss(graph_emb)
            loss = loss + DECorR_WEIGHT * loss_decorr

            optimizer.zero_grad()
            loss.backward()
            torch.nn.utils.clip_grad_norm_(model.parameters(), max_norm=2.0)
            optimizer.step()

            total_loss += loss.item() * batch.num_graphs
            preds = out.argmax(dim=1)
            all_preds.extend(preds.cpu().numpy())
            all_labels.extend(batch.y.cpu().numpy())

        train_acc = accuracy_score(all_labels, all_preds)
        train_loss = total_loss / len(train_graphs)

        scheduler.step()

        # NEW: SWA weight update
        if epoch >= SWA_START:
            if not swa_active:
                swa_active = True
                print(f"  -> SWA activated at epoch {epoch}")
            with torch.no_grad():
                swa_n += 1
                for p_swa, p_model in zip(swa_model.parameters(), model.parameters()):
                    p_swa.data = (p_swa.data * (swa_n - 1) + p_model.data) / swa_n
                for b_swa, b_model in zip(swa_model.buffers(), model.buffers()):
                    b_swa.data = b_model.data

        # Validation
        model.eval()
        val_preds, val_labels, val_probs = [], [], []
        with torch.no_grad():
            for batch in val_loader:
                batch = batch.to(device)
                pca_U, pca_D = online_pca.get_components(n=online_pca.n_components)
                pca_comps = [
                    torch.from_numpy(pca_U[:, i].reshape(N_ROIS, N_ROIS)).float().to(device)
                    for i in range(pca_U.shape[1])
                ]
                out, _, _, _ = model(batch, pca_comps)
                probs = F.softmax(out, dim=1)
                preds = probs.argmax(dim=1)
                val_preds.extend(preds.cpu().numpy())
                val_labels.extend(batch.y.cpu().numpy())
                val_probs.extend(probs[:, 1].cpu().numpy())

        val_acc = accuracy_score(val_labels, val_preds)
        val_f1 = f1_score(val_labels, val_preds, average='binary')

        # Evaluate SWA model on validation
        if swa_active:
            swa_model.eval()
            swa_preds, swa_labels = [], []
            with torch.no_grad():
                for batch in val_loader:
                    batch = batch.to(device)
                    pca_U, pca_D = online_pca.get_components(n=online_pca.n_components)
                    pca_comps = [
                        torch.from_numpy(pca_U[:, i].reshape(N_ROIS, N_ROIS)).float().to(device)
                        for i in range(pca_U.shape[1])
                    ]
                    out, _, _, _ = swa_model(batch, pca_comps)
                    preds = out.argmax(dim=1)
                    swa_preds.extend(preds.cpu().numpy())
                    swa_labels.extend(batch.y.cpu().numpy())
            swa_val_f1 = f1_score(swa_labels, swa_preds, average='binary')
            swa_val_acc = accuracy_score(swa_labels, swa_preds)
        else:
            swa_val_f1 = 0
            swa_val_acc = 0

        current_lr = optimizer.param_groups[0]['lr']

        if epoch % 10 == 0 or epoch == 1:
            swa_str = f" | SWA Val F1: {swa_val_f1:.4f}" if swa_active else ""
            print(f"Epoch {epoch:3d} | Train Loss: {train_loss:.4f} | "
                  f"Train Acc: {train_acc:.4f} | Val Acc: {val_acc:.4f} | "
                  f"Val F1: {val_f1:.4f} | LR: {current_lr:.6f}{swa_str}")

        # Use max of regular and SWA validation F1 for best model selection
        best_f1_this_epoch = max(val_f1, swa_val_f1)
        use_swa_for_test = swa_active and swa_val_f1 > val_f1

        if best_f1_this_epoch > best_val_f1:
            best_val_f1 = best_f1_this_epoch
            patience_counter = 0
            eval_model = swa_model if use_swa_for_test else model

            eval_model.eval()
            test_preds, test_labels, test_probs = [], [], []
            with torch.no_grad():
                for batch in test_loader:
                    batch = batch.to(device)
                    pca_U, pca_D = online_pca.get_components(n=online_pca.n_components)
                    pca_comps = [
                        torch.from_numpy(pca_U[:, i].reshape(N_ROIS, N_ROIS)).float().to(device)
                        for i in range(pca_U.shape[1])
                    ]
                    out, _, _, _ = eval_model(batch, pca_comps)
                    probs = F.softmax(out, dim=1)
                    preds = probs.argmax(dim=1)
                    test_preds.extend(preds.cpu().numpy())
                    test_labels.extend(batch.y.cpu().numpy())
                    test_probs.extend(probs[:, 1].cpu().numpy())
            test_acc = accuracy_score(test_labels, test_preds)
            test_f1 = f1_score(test_labels, test_preds, average='binary')
            test_auc = roc_auc_score(test_labels, test_probs) if len(set(test_labels)) > 1 else 0.5
            model_type = "SWA" if use_swa_for_test else "REG"
            print(f"  -> New best [{model_type}]! Test Acc: {test_acc:.4f} | "
                  f"F1: {test_f1:.4f} | AUC: {test_auc:.4f}")
            best_test_metrics = (test_acc, test_f1, test_auc)
        else:
            patience_counter += 1
            if patience_counter >= PATIENCE:
                print(f"Early stopping at epoch {epoch}")
                break

    # Final: try SWA model if not already used as best
    if swa_active and best_test_metrics:
        swa_model.eval()
        test_preds, test_labels, test_probs = [], [], []
        with torch.no_grad():
            for batch in test_loader:
                batch = batch.to(device)
                pca_U, pca_D = online_pca.get_components(n=online_pca.n_components)
                pca_comps = [
                    torch.from_numpy(pca_U[:, i].reshape(N_ROIS, N_ROIS)).float().to(device)
                    for i in range(pca_U.shape[1])
                ]
                out, _, _, _ = swa_model(batch, pca_comps)
                probs = F.softmax(out, dim=1)
                preds = probs.argmax(dim=1)
                test_preds.extend(preds.cpu().numpy())
                test_labels.extend(batch.y.cpu().numpy())
                test_probs.extend(probs[:, 1].cpu().numpy())
        swa_test_acc = accuracy_score(test_labels, test_preds)
        swa_test_f1 = f1_score(test_labels, test_preds, average='binary')
        swa_test_auc = roc_auc_score(test_labels, test_probs) if len(set(test_labels)) > 1 else 0.5
        print(f"  -> SWA final eval: Test Acc: {swa_test_acc:.4f} | "
              f"F1: {swa_test_f1:.4f} | AUC: {swa_test_auc:.4f}")
        if swa_test_f1 > best_test_metrics[1]:
            best_test_metrics = (swa_test_acc, swa_test_f1, swa_test_auc)

    return best_test_metrics


# ============================================================
# Main (FIXED: augmentation for training set only)
# ============================================================
def main():
    print("\n[IGA] Independent Graph Analysis with Online PCA + Hybrid PCA-ICA")
    print("[FIXED] Mixup + SWA + Cosine Annealing + Augmentation + PCA Injection")
    X_all, Y_all, demo_all = load_data(use_ica=True)
    valid_indices = [i for i, x in enumerate(X_all) if x.shape[1] >= WINDOW_SIZE]
    X_all = X_all[valid_indices]
    Y_all = Y_all[valid_indices]
    demo_all = demo_all[valid_indices]
    print(f"Using {len(X_all)} subjects")

    n_features = N_ROIS * N_ROIS
    online_pca = OnlineGraphPCA(n_features, n_components=20, amnesic_factor=0)

    skf = StratifiedKFold(n_splits=N_SPLITS, shuffle=True, random_state=SEED)
    results = []

    for fold, (train_idx, test_idx) in enumerate(skf.split(X_all, Y_all)):
        train_subjects = X_all[train_idx]
        train_labels = Y_all[train_idx]
        train_demo = demo_all[train_idx]
        test_subjects = X_all[test_idx]
        test_labels = Y_all[test_idx]
        test_demo = demo_all[test_idx]

        train_val_idx, val_idx = train_test_split(
            np.arange(len(train_subjects)), test_size=0.2,
            stratify=train_labels, random_state=SEED
        )
        tr_sub = train_subjects[train_val_idx]
        tr_lab = train_labels[train_val_idx]
        tr_dem = train_demo[train_val_idx]
        val_sub = train_subjects[val_idx]
        val_lab = train_labels[val_idx]
        val_dem = train_demo[val_idx]

        print(f"\nBuilding graphs for fold {fold+1}...")
        # FIX: Enable augmentation for TRAINING ONLY (was False for all)
        train_graphs = build_graphs_iga(tr_sub, tr_dem, tr_lab, WINDOW_SIZE, STRIDE,
                                        use_augmentation=USE_AUGMENTATION_TRAIN)
        val_graphs = build_graphs_iga(val_sub, val_dem, val_lab, WINDOW_SIZE, STRIDE,
                                     use_augmentation=False)
        test_graphs = build_graphs_iga(test_subjects, test_demo, test_labels,
                                       WINDOW_SIZE, STRIDE, use_augmentation=False)

        print("Updating Online PCA with training graphs...")
        for g in train_graphs:
            adj_np = g.adj_matrix.numpy()
            online_pca.update(adj_np.flatten())
        print("Online PCA updated.")

        fold_res = train_fold_iga(train_graphs, val_graphs, test_graphs, fold+1, online_pca)
        if fold_res:
            results.append(fold_res)

        del train_graphs, val_graphs, test_graphs
        if torch.cuda.is_available():
            torch.cuda.empty_cache()

    if results:
        results = np.array(results)
        print("\n" + "="*60)
        print("FINAL IGA RESULTS")
        print("="*60)
        print(f"Accuracy:  {results[:, 0].mean():.4f} +/- {results[:, 0].std():.4f}")
        print(f"F1 Score:  {results[:, 1].mean():.4f} +/- {results[:, 1].std():.4f}")
        print(f"AUC:       {results[:, 2].mean():.4f} +/- {results[:, 2].std():.4f}")
        print("="*60)
        results_df = pd.DataFrame(results, columns=['Accuracy', 'F1', 'AUC'])
        results_df.to_csv("iga_results.csv", index=False)
        print("Results saved to iga_results.csv")


if __name__ == "__main__":
    main()